language: node_js
node_js:
- '0.11'
- '0.10'
before_deploy:
- gulp build
deploy:
  provider: npm
  skip_cleanup: true
  email: k88hudson@gmail.com
  api_key:
    secure: EW60vg8ny/HMvUctRjoLqZxrw6LUaYdU0DEkD454yqJAR6O64aXqh1H9hJNUice2y3mVD/FHBPIXLqlDeurPnSkG3e4T1FuMhKN5KcTWg3s7QX34KsX2eSrKUcv2yY0jNcq8o765thgKhwBYCdXpyCLQ68IQ4SB0NiCiOvRxWPM=
  on:
    tags: true
    all_branches: true
    repo: k88hudson/banana-banana
